### ISSUE TITLE
Can't use PermissionRequiredMixin with a CreateView

### ISSUE THREAD

**Issue by aidanlister** [django-guardian/django-guardian#279]
Even though you'd think CreateView doesn't define a get_object, it does (via SingleObjectMixin via ModelFormMixin), then Guardian raises this error:

    Generic detail view PropertyCreateView must be called with either an object pk or a slug

You can get around this by defining a ```get_object(self): return None``` ... but there should be an override for Guardian maybe "use_object_permissions" which can be set to False. That way, we can use PermissionRequiredMixin for all of our views, not just ones with SingleObjectMixin.

**Comment by mobula** [comment]
+1 - my own workaround is to use `django.contrib.auth.permission_required` from auth on the `dispatch()` method. 

```
class TestimonialCreateView(generic.CreateView):
    model = Testimonial

    # Using auth.permission_required
    # raise_exception set to True do avoid infinite loop on login
    # guardian doesn't deal well with CreateView (when obj pk not set)
    @method_decorator(login_required)
    @method_decorator(permission_required('news.add_testimonial', raise_exception=True))
    def dispatch(self, *args, **kwargs):
       return super(TestimonialCreateView, self).dispatch(*args, **kwargs)
```

**Comment by ofilipowicz** [comment]
How about this issue? Still can't use this mixin in CreateView.

**Comment by aidanlister** [comment]
Just define a def get_object: return None and it works fine

**Comment by brianmay** [comment]
I believe this is a duplicate of #146, so closing this report.

**Comment by ad-m** [comment]
Fixed. See #448, #433,

**Comment by Braintelligence** [comment]
This is still happening for me in django-guardian 2.4.0
Everything worked fine until I added PermissionRequiredMixin to my CreateView.

Any ideas?

**Comment by stefflc** [comment]
> This is still happening for me in django-guardian 2.4.0 Everything worked fine until I added PermissionRequiredMixin to my CreateView.
> 
> Any ideas other than
> 
> ```
> def get_object(self):
>   return None
> ```
> 
> ?

Hi,
I also found that overriding get_permission_object() will also work.
```
def get_permission_object(self):
      return None
``` 
If you look at the `PermissionRequiredMixin` documentation it says that `PermissionREquiredMixin.permission_object` pulls from self.get_permission() which pulls from `self.get_object()` or `self.object` by default

**Comment by j2l** [comment]
Hello,
Happening to me on fresh Django 5.0.6 and 4.0.10 with django-guardian     2.4.0
```python
    permission_required = 'app1.can_add'
    accept_global_perms = True
    def get_permission_object(self):
      return None
```
throws “The page isn’t redirecting properly”
