### ISSUE TITLE
Django 1.8 GuardedModelAdminMixin.get_queryset exception

### ISSUE THREAD

**Issue by lalstef** [django-guardian/django-guardian#307]
Hi,

I'm using django-guardian (through django-userena) with Django 1.8. When trying to access User model in django admin, GuardedModelAdminMixin raises the following Exception:

`'super' object has no attribute 'queryset'`

In `GuardedModelAdminMixin.get_queryset` the problematic code is:
```
    def get_queryset(self, request):
        # Prefer the Django >= 1.6 interface but maintain
        # backward compatibility
        method = getattr(
            super(GuardedModelAdminMixin, self), 'get_queryset',
            super(GuardedModelAdminMixin, self).queryset)

```
In Django 1.8 (I guess in all Django >= 1.6) `queryset` method does not exist, but this part

`super(GuardedModelAdminMixin, self).queryset` is evaluated and raising Exception even though `get_queryset` method exists and it's found.

**Comment by frwickst** [comment]
The problem here is that `super(GuardedModelAdminMixin, self).queryset` is not defined in Django 1.8. Even if get_queryset is, getattr will still fail as we have a undefined variable as the last paramter.
Example of what the code basically does:
```python
class Test(object):
    a = 'test string'

t = Test()
getattr(t, 'a')
>> 'test string'
getattr(t, 'a', Test.b)
>> AttributeError: type object 'Test' has no attribute 'b'
```
What we could do is something like:
```
    def get_queryset(self, request):
        # Prefer the Django >= 1.6 interface but maintain
        # backward compatibility
        method = getattr(
            super(GuardedModelAdminMixin, self), 'get_queryset',
            getattr(super(GuardedModelAdminMixin, self), 'queryset', None))
    qs = method(request)
```
This of course can make the code that calls `method` crash as well, as if we set it to None the `qs` declaration would fail. This might not we a big issue however as `method` should not be set to None in any known Django version to date.
I'll create a pull request with this fix and see if @lukaszb accepts this solution.

**Comment by mcgeeco** [comment]
Would be great to get this merged. Just out of curiosity - is there really a need to maintain compatibility with such old versions of Django on new releases? Especially since it's stuff Django itself has removed back-compatibility for.

**Comment by HEdingfield** [comment]
@mcgeeco Agreed, seems like the docs could just point users of 1.6 or whatever to download an older version.

**Comment by Karlheinzniebuhr** [comment]
having the same issue, solution didn't work for me

**Comment by autrilla** [comment]
This has not been fixed yet, has it? I could make a PR for it, the fix is really simple.

**Comment by mcgeeco** [comment]
@autrillia I believe the fix has been merged to the development branch, but not the release branch. I'm not sure what the delay is, though.

**Comment by frwickst** [comment]
@autrilla Yes, if you follow the references down the rabbit hole you will find that there are some pull-requests already created for this issue.
First we have: #311 that got merged, this one did not go all the way however and was merged per-maturely.
We then have #321 that should fix the things that was left undone in #311 

It looks like @lukaszb has frozen the release already, which is a shame since there are still some Django 1.8 bugs left in there.

I really hope that #310 gets a done so that pull-requests start getting merged and new builds is pushed to PyPi

**Comment by HEdingfield** [comment]
Seems to me like this (and possibly #315) was resolved with release 1.3.

**Comment by thedrow** [comment]
@lukaszb Was this resolved? It is in 1.3? Can we close it?

**Comment by dgabrielson** [comment]
This problem still exists in django-guardian 1.3 as downloaded from PyPi.

**Comment by Wtower** [comment]
Same issue for me as well, subscribing.

**Comment by jaredtritz** [comment]
Ran into the same problem: "object has no attribute 'queryset'" when trying to use the admin for setting permission of instance.

**Comment by ccogdon** [comment]
One workaround which seems to work is this:

```python
from functools import partial

...

class GuardedModelAdmin2(GuardedModelAdmin):
    @property
    def queryset(self):
        return partial(self.get_queryset)
```

**Comment by jlark** [comment]
Having the same issue here on 1.8 having downloaded from pypi.

**Comment by frwickst** [comment]
I'm hoping that #321 will fix this and that it will be merged some time soon. I'm really hoping that @lukaszb will consider #310 so that we can get things merged asap instead of having to wait weeks/months for merges.

Please go and up-vote #310 :)

**Comment by lucasdavid** [comment]
@ccogdon workaround works for me, although I've overridden `GuardedModelAdminMixin` class and then mixed with a new `GuardedModelAdmin` definition - so I can mix it with `admin.UserAdmin` classes as well.

I'd appreciate if anyone could point out possible side-effects from this!

```py
from django.contrib import admin
from guardian import admin as guardian_admin
from functools import partial


class GuardedModelAdminMixin(guardian_admin.GuardedModelAdminMixin):
    @property
    def queryset(self):
        return partial(self.get_queryset)


class GuardedModelAdmin(GuardedModelAdminMixin, admin.ModelAdmin):
    """Extend this class if your model is guarded by Guardian (per-object authorization).

    This class is a workaround for Django-1.8.
    See more at issue #307 https://github.com/django-guardian/django-guardian/issues/307
    """
```

**Comment by brianmay** [comment]
I believe this is fixed in 56ae038bb76e31122acf81542f0386dde888b6e5.
